apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-example-deploy-java-multizone
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: Java multizone networking module
  source:
    repo: https://github.com/GoogleCloudPlatform/terraform-example-deploy-java-multizone.git
    sourceType: git
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  description:
    tagline: This module deploys the networking resources required for this HSA
  examples:
  - name: simple_example
    location: examples/simple_example
  variables:
  - name: firewall_source_ranges
    description: The firewall will apply only to traffic that has source IP address in these ranges. These ranges must be expressed in CIDR format.
    type: list(string)
    default: []
    required: false
  - name: project_id
    description: GCP project ID.
    type: string
    required: true
  - name: region
    description: The region chosen to be used.
    type: string
    required: true
  - name: xwiki_vm_tag
    description: Tag for targeting FW rule
    type: string
    required: true
  outputs:
  - name: xwiki_private_network
    description: VPC network
  roles:
  - level: Project
    roles:
    - roles/owner
  services:
  - cloudresourcemanager.googleapis.com
  - iam.googleapis.com
  - storage.googleapis.com
  - serviceusage.googleapis.com
  - compute.googleapis.com
  - logging.googleapis.com
  - sqladmin.googleapis.com
  - cloudbuild.googleapis.com
  - file.googleapis.com
  - servicenetworking.googleapis.com
  - monitoring.googleapis.com
