apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-example-deploy-java-multizone
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: Java multizone filestore module
  source:
    repo: https://github.com/GoogleCloudPlatform/terraform-example-deploy-java-multizone.git
    sourceType: git
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  description:
    tagline: This module deploys the filestore instance required for this HSA
  examples:
  - name: simple_example
    location: examples/simple_example
  variables:
  - name: private_network_id
    description: VPC id
    type: string
    required: true
  - name: zone
    description: zone is used by filestore location, it depends on the region chosen.
    type: string
    required: true
  outputs:
  - name: filestore_ip
    description: Filestore IP address
  roles:
  - level: Project
    roles:
    - roles/owner
  services:
  - cloudresourcemanager.googleapis.com
  - iam.googleapis.com
  - storage.googleapis.com
  - serviceusage.googleapis.com
  - compute.googleapis.com
  - logging.googleapis.com
  - sqladmin.googleapis.com
  - cloudbuild.googleapis.com
  - file.googleapis.com
  - servicenetworking.googleapis.com
  - monitoring.googleapis.com
